[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "B6vGDhganemog1R3f98vCj3ZYzzg1gMHeafgsCsB2mPY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elizabetheidelson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
